export type Language = "en" | "pt" | "es" | "fr" | "de" | "it";

export interface PlanTranslation {
  name: string;
  target: string;
  desc: string;
  features: string[];
  cta: string;
}

export interface TranslationDict {
  // Navigation & Top Bar
  navChatbot: string;
  navStaffDesk: string;
  navDirectory: string;
  navKnowledge: string;
  navEmbed: string;
  navPricing: string;
  tagline: string;
  demoBadge: string;
  liveBadge: string;
  trialNotice: string;
  trialDays: string;
  footerRights: string;
  footerCapabilities: string;

  // Staff Desk View
  staffTitle: string;
  staffSubtitle: string;
  filterAll: string;
  filterHousekeeping: string;
  filterMaintenance: string;
  filterLateCheckout: string;
  filterRoomService: string;
  filterGeneral: string;
  statusAll: string;
  statusPending: string;
  statusInProgress: string;
  statusCompleted: string;
  searchPlaceholder: string;
  createTicketBtn: string;
  refreshBtn: string;
  noTicketsTitle: string;
  noTicketsSubtitle: string;
  roomLabel: string;
  guestLabel: string;
  categoryLabel: string;
  titleLabel: string;
  descLabel: string;
  cancelBtn: string;
  submitTicketBtn: string;
  newTicketModalTitle: string;

  // Hotel Directory View
  directoryTitle: string;
  directorySubtitle: string;
  tabDining: string;
  tabAmenities: string;
  tabAttractions: string;
  tabPolicies: string;
  searchMenuPlaceholder: string;
  orderViaChatbot: string;
  askChatbotPrompt: string;
  favoriteBadge: string;
  serviceIncluded: string;
  breakfastTitle: string;
  poolSpaTitle: string;
  gymTitle: string;
  parkingTitle: string;

  // Knowledge Base View
  kbTitle: string;
  kbSubtitle: string;
  kbSaveSuccess: string;
  kbSaveBtn: string;
  kbResetBtn: string;
  hotelNameLabel: string;
  defaultLangLabel: string;
  wifiNetLabel: string;
  wifiPassLabel: string;
  checkInLabel: string;
  checkOutLabel: string;
  breakfastHoursLabel: string;
  breakfastLocationLabel: string;
  poolHoursLabel: string;
  spaHoursLabel: string;
  gymHoursLabel: string;
  roomServiceHoursLabel: string;
  petPolicyLabel: string;
  smokingPolicyLabel: string;
  luggagePolicyLabel: string;
  parkingDetailsLabel: string;
  localAttractionsLabel: string;
  lateCheckoutPolicyLabel: string;
  customPromptLabel: string;

  // Embed & QR View
  embedTitle: string;
  embedSubtitle: string;
  cardPreviewTitle: string;
  cardPreviewSubtitle: string;
  downloadPdfBtn: string;
  copyUrlBtn: string;
  copiedNotice: string;
  howItWorksStep1: string;
  howItWorksStep2: string;
  howItWorksStep3: string;
  guestFacingUrlLabel: string;
  roomNumberPlaceholder: string;
  guestSurnamePlaceholder: string;

  // Pricing Plans View
  pricingTitle: string;
  pricingSubtitle: string;
  monthlyBilling: string;
  annualBilling: string;
  saveBadge: string;
  billedAnnually: string;
  billedMonthly: string;
  monthlyPerUnit: string;
  noCommitment: string;
  freeSetupBadge: string;
  setupFeeLabel: string;
  planPopularBadge: string;
  
  plans: {
    starter: PlanTranslation;
    boutique: PlanTranslation;
    enterprise: PlanTranslation;
  };

  // ROI Calculator
  roiTitle: string;
  roiSubtitle: string;
  roomCountLabel: string;
  frontDeskSavingsLabel: string;
  upsellRevenueLabel: string;
  softwareCostLabel: string;
  netRoiLabel: string;
  roiExplanation: string;

  // Onboarding Modal
  modalTitle: string;
  modalSubtitle: string;
  modalHotelName: string;
  modalContactName: string;
  modalEmail: string;
  modalPhone: string;
  modalNotes: string;
  modalSubmit: string;
  modalSuccessTitle: string;
  modalSuccessDesc: string;
  modalClose: string;
}

export const translations: Record<Language, TranslationDict> = {
  en: {
    navChatbot: "Guest Concierge",
    navStaffDesk: "Staff Desk & Tickets",
    navDirectory: "Hotel Directory",
    navKnowledge: "AI Knowledge Base",
    navEmbed: "Widget & QR Codes",
    navPricing: "SaaS Plans & Pricing",
    tagline: "Multilingual AI Guest Concierge & Operations Platform",
    demoBadge: "Interactive Live Demo",
    liveBadge: "Active 24/7",
    trialNotice: "🔥 Limited Offer: 7-Day Free Pilot on 2 Rooms (No Credit Card Required)",
    trialDays: "7-Day Free Trial",
    footerRights: "© 2026 Grand Concierge AI SaaS. Built for Luxury Hotels, STRs & Boutique B&Bs.",
    footerCapabilities: "6 Native Languages • 24/7 Autonomous Operations • Instant Stripe Checkout",

    staffTitle: "Front Desk Ticket & Operations Queue",
    staffSubtitle: "Real-time housekeeping, maintenance, room service & late checkout requests generated by guests via AI.",
    filterAll: "All Categories",
    filterHousekeeping: "Housekeeping",
    filterMaintenance: "Maintenance",
    filterLateCheckout: "Late Check-out",
    filterRoomService: "Room Service",
    filterGeneral: "General Inquiries",
    statusAll: "All Statuses",
    statusPending: "Pending",
    statusInProgress: "In Progress",
    statusCompleted: "Completed",
    searchPlaceholder: "Search by room #, guest name, or request details...",
    createTicketBtn: "+ Create Manual Ticket",
    refreshBtn: "Refresh List",
    noTicketsTitle: "No Tickets Found",
    noTicketsSubtitle: "There are no tickets matching your current filter. Incoming guest requests will appear here instantly.",
    roomLabel: "Room #",
    guestLabel: "Guest Name",
    categoryLabel: "Department",
    titleLabel: "Ticket Title",
    descLabel: "Details & Notes",
    cancelBtn: "Cancel",
    submitTicketBtn: "Register Ticket",
    newTicketModalTitle: "Create New Staff Request",

    directoryTitle: "Hotel Amenities, Dining & Guest Guide",
    directorySubtitle: "Complete directory of dining menus, wellness facilities, hotel policies and local attractions.",
    tabDining: "Dining & Room Service",
    tabAmenities: "Pool, Spa & Wellness",
    tabAttractions: "Local Attractions & Tours",
    tabPolicies: "Hotel Policies & Reception",
    searchMenuPlaceholder: "Search restaurant & bar menu...",
    orderViaChatbot: "Order via Concierge",
    askChatbotPrompt: "Ask Concierge about",
    favoriteBadge: "Popular",
    serviceIncluded: "Room service delivery included.",
    breakfastTitle: "Atlantic Buffet Breakfast",
    poolSpaTitle: "Heated Pools & Wellness Spa",
    gymTitle: "Fitness Center Technogym",
    parkingTitle: "Underground Garage & EV Chargers",

    kbTitle: "Hotel Profile & Knowledge Base Training",
    kbSubtitle: "Configure Wi-Fi, dining schedules, amenities and operational guidelines. The AI assistant grounds 100% of responses on this data.",
    kbSaveSuccess: "Profile and knowledge base saved successfully!",
    kbSaveBtn: "Save Changes",
    kbResetBtn: "Reset to Default",
    hotelNameLabel: "Hotel / Property Name",
    defaultLangLabel: "Default Language",
    wifiNetLabel: "Wi-Fi Network Name (SSID)",
    wifiPassLabel: "Wi-Fi Access Instructions",
    checkInLabel: "Check-in Time",
    checkOutLabel: "Check-out Time",
    breakfastHoursLabel: "Breakfast Hours",
    breakfastLocationLabel: "Breakfast Location",
    poolHoursLabel: "Pool Opening Hours",
    spaHoursLabel: "Spa & Thalasso Hours",
    gymHoursLabel: "Gym & Fitness Hours",
    roomServiceHoursLabel: "Room Service Hours",
    petPolicyLabel: "Pet Policy",
    smokingPolicyLabel: "Smoking Policy",
    luggagePolicyLabel: "Luggage Storage Policy",
    parkingDetailsLabel: "Parking & EV Details",
    localAttractionsLabel: "Local Attractions & Recommendations",
    lateCheckoutPolicyLabel: "Late Check-out Policy & Fees",
    customPromptLabel: "Custom AI System Prompt & Personality",

    embedTitle: "In-Room QR Code & Digital Concierge Access",
    embedSubtitle: "Generate high-resolution printable QR code stands for nightstands, desks, and keycards.",
    cardPreviewTitle: "In-Room Acrylic Standee Preview",
    cardPreviewSubtitle: "Print and place on the bedside table for instant guest onboarding.",
    downloadPdfBtn: "Download High-Res PDF Standee",
    copyUrlBtn: "Copy Guest Link",
    copiedNotice: "Link copied to clipboard!",
    howItWorksStep1: "1. Guest scans QR code with smartphone (no app installation needed)",
    howItWorksStep2: "2. Concierge opens instantly in guest's native language",
    howItWorksStep3: "3. Requests (towels, late checkout, dining) arrive live at front desk",
    guestFacingUrlLabel: "Live Guest Direct Web Link",
    roomNumberPlaceholder: "Room 402",
    guestSurnamePlaceholder: "Silva",

    pricingTitle: "Transparent Plans for Any Property Size",
    pricingSubtitle: "Scale 5-star guest satisfaction while automating 80% of front-desk inquiries.",
    monthlyBilling: "Monthly Billing",
    annualBilling: "Annual Billing",
    saveBadge: "Save 20% + Free Setup",
    billedAnnually: "Billed annually",
    billedMonthly: "Billed monthly",
    monthlyPerUnit: "/ mo",
    noCommitment: "No long-term contract • Cancel anytime",
    freeSetupBadge: "FREE 🎁",
    setupFeeLabel: "Setup Fee:",
    planPopularBadge: "Most Popular",

    plans: {
      starter: {
        name: "Starter (Airbnb & STR)",
        target: "Individual properties & Superhosts (1 to 3 units)",
        desc: "Ideal for hosts looking to automate late-night guest questions and check-in instructions.",
        features: [
          "1 to 3 Rooms / Apartments",
          "6-Language Autonomous AI Concierge",
          "Printable High-Res QR Codes",
          "Automated Wi-Fi & Check-in Guides",
          "Email & Ticket Notifications",
          "99.9% Uptime Guarantee"
        ],
        cta: "Start 7-Day Pilot / Get Started"
      },
      boutique: {
        name: "Boutique Hotel",
        target: "Boutique hotels, Inns & B&Bs (4 to 25 rooms)",
        desc: "The complete guest intelligence system: live ticket desk, room service upselling, and voice interactions.",
        features: [
          "Up to 25 Rooms / Suites",
          "Real-time Front Desk Staff Queue",
          "Voice AI Interaction & Audio Output",
          "Room Service & Late Check-out Upselling",
          "Custom Knowledge Base & Menu Editor",
          "Priority 24/7 WhatsApp Support"
        ],
        cta: "Start 7-Day Pilot / Subscribe"
      },
      enterprise: {
        name: "Resort & Enterprise",
        target: "Resorts, Hotel Chains & Property Managers (25+ units)",
        desc: "Enterprise hospitality infrastructure with multi-property management, PMS sync, and custom SLA.",
        features: [
          "Unlimited Rooms & Properties",
          "Multi-property Central Admin",
          "PMS / Channel Manager Webhooks",
          "Dedicated Account Manager",
          "Staff Role-Based Access Control",
          "Custom Domain (concierge.yourhotel.com)"
        ],
        cta: "Request Enterprise Pilot"
      }
    },

    roiTitle: "Return on Investment (ROI) Calculator",
    roiSubtitle: "Calculate how much your property saves in labor hours and earns in extra guest upselling.",
    roomCountLabel: "Number of Rooms / Units:",
    frontDeskSavingsLabel: "Staff Labor Hours Saved",
    upsellRevenueLabel: "Extra Upsell Revenue (F&B / Late Out)",
    softwareCostLabel: "Software Cost",
    netRoiLabel: "Estimated Net Monthly Value",
    roiExplanation: "Based on hospitality industry averages: saves ~2.5 front-desk hours/room/month at $20/hr, plus generates ~$35/room/month in room service & late checkout upgrades.",

    modalTitle: "Start Free 7-Day Pilot / Onboarding",
    modalSubtitle: "Test Grand Concierge AI on 2 rooms for 7 days with zero obligation.",
    modalHotelName: "Hotel / Property Name",
    modalContactName: "Contact Person & Role",
    modalEmail: "Business Email",
    modalPhone: "WhatsApp / Phone",
    modalNotes: "Special requests or property details",
    modalSubmit: "Confirm & Request 7-Day Pilot",
    modalSuccessTitle: "Pilot Request Received!",
    modalSuccessDesc: "Our hospitality onboarding team will reach out in under 2 hours to activate your QR stands and customize your knowledge base.",
    modalClose: "Close"
  },

  pt: {
    navChatbot: "Concierge do Hóspede",
    navStaffDesk: "Painel da Receção & Pedidos",
    navDirectory: "Diretório do Hotel",
    navKnowledge: "Base de Conhecimento IA",
    navEmbed: "Widget & Códigos QR",
    navPricing: "Planos & Preços",
    tagline: "Concierge Multilíngue de IA & Gestão de Pedidos",
    demoBadge: "Modelo de Demonstração Ao Vivo",
    liveBadge: "Ativo 24/7",
    trialNotice: "🔥 Oferta Especial: Teste Piloto Gratuito de 7 Dias em 2 Quartos (Sem Cartão de Crédito)",
    trialDays: "7 Dias de Teste Grátis",
    footerRights: "© 2026 Grand Concierge AI SaaS. Desenvolvido para Hotéis de Luxo, ALs & B&Bs.",
    footerCapabilities: "6 Idiomas Nativos • Atendimento 24/7 Autônomo • Checkout Stripe Imediato",

    staffTitle: "Fila de Pedidos & Operações da Receção",
    staffSubtitle: "Pedidos de governança, manutenção, room service e late check-out gerados em tempo real pela IA.",
    filterAll: "Todas as Categorias",
    filterHousekeeping: "Governança (Limpeza/Toalhas)",
    filterMaintenance: "Manutenção",
    filterLateCheckout: "Late Check-out",
    filterRoomService: "Room Service",
    filterGeneral: "Geral / Concierge",
    statusAll: "Todos os Estados",
    statusPending: "Pendente",
    statusInProgress: "Em Andamento",
    statusCompleted: "Concluído",
    searchPlaceholder: "Pesquisar por nº quarto, hóspede ou detalhes...",
    createTicketBtn: "+ Criar Ticket Manual",
    refreshBtn: "Atualizar Lista",
    noTicketsTitle: "Nenhum Pedido Encontrado",
    noTicketsSubtitle: "Não existem pedidos com os filtros selecionados. Novos pedidos enviados pelos hóspedes no chat aparecerão aqui instantaneamente.",
    roomLabel: "Nº Quarto",
    guestLabel: "Nome do Hóspede",
    categoryLabel: "Departamento",
    titleLabel: "Título do Pedido",
    descLabel: "Detalhes e Observações",
    cancelBtn: "Cancelar",
    submitTicketBtn: "Registar Ticket",
    newTicketModalTitle: "Criar Novo Pedido de Staff",

    directoryTitle: "Comodidades, Guia Gastronómico & Serviços",
    directorySubtitle: "Guia completo de ementas, bem-estar, regras do hotel e pontos de interesse locais.",
    tabDining: "Restauração & Room Service",
    tabAmenities: "Piscinas, Spa & Bem-Estar",
    tabAttractions: "Atrações Locais & Passeios",
    tabPolicies: "Políticas do Hotel & Receção",
    searchMenuPlaceholder: "Pesquisar ementa do restaurante & bar...",
    orderViaChatbot: "Pedir via Concierge",
    askChatbotPrompt: "Perguntar ao Concierge sobre",
    favoriteBadge: "Favorito",
    serviceIncluded: "Taxa de entrega no quarto incluída.",
    breakfastTitle: "Pequeno-Almoço Buffet Atlântico",
    poolSpaTitle: "Piscinas Aquecidas & Marina Spa",
    gymTitle: "Ginásio & Fitness Technogym",
    parkingTitle: "Parque Subterrâneo & Carregadores EV",

    kbTitle: "Perfil do Hotel & Treino da Base de IA",
    kbSubtitle: "Configure Wi-Fi, horários de refeições, comodidades e regras. O assistente baseia 100% das respostas nestes dados.",
    kbSaveSuccess: "Perfil e base de conhecimento guardados com sucesso!",
    kbSaveBtn: "Guardar Alterações",
    kbResetBtn: "Restaurar Padrão",
    hotelNameLabel: "Nome do Hotel / Propriedade",
    defaultLangLabel: "Idioma Padrão",
    wifiNetLabel: "Nome da Rede Wi-Fi (SSID)",
    wifiPassLabel: "Instruções de Acesso Wi-Fi",
    checkInLabel: "Horário de Check-in",
    checkOutLabel: "Horário de Check-out",
    breakfastHoursLabel: "Horário do Pequeno-Almoço",
    breakfastLocationLabel: "Local do Pequeno-Almoço",
    poolHoursLabel: "Horário das Piscinas",
    spaHoursLabel: "Horário do Spa & Talassoterapia",
    gymHoursLabel: "Horário do Ginásio",
    roomServiceHoursLabel: "Horário de Room Service",
    petPolicyLabel: "Política de Animais",
    smokingPolicyLabel: "Política de Fumo",
    luggagePolicyLabel: "Política de Bagagens",
    parkingDetailsLabel: "Estacionamento & Carregador EV",
    localAttractionsLabel: "Atrações e Dicas Locais",
    lateCheckoutPolicyLabel: "Política de Late Check-out & Taxas",
    customPromptLabel: "Prompt de Sistema Personalizado",

    embedTitle: "Código QR do Quarto & Acesso ao Concierge",
    embedSubtitle: "Gere expositores em código QR de alta resolução para colocar na mesa de cabeceira e cartões.",
    cardPreviewTitle: "Pré-visualização do Expositor de Quarto",
    cardPreviewSubtitle: "Imprima e coloque no quarto para ativação imediata pelo hóspede.",
    downloadPdfBtn: "Descarregar Expositor em PDF (Alta Resolução)",
    copyUrlBtn: "Copiar Link do Hóspede",
    copiedNotice: "Link copiado com sucesso!",
    howItWorksStep1: "1. O hóspede lê o QR code com o telemóvel (sem instalar apps)",
    howItWorksStep2: "2. O concierge abre instantaneamente no idioma nativo do hóspede",
    howItWorksStep3: "3. Os pedidos (toalhas, late checkout, comida) entram na receção",
    guestFacingUrlLabel: "Link Direto de Acesso para o Hóspede",
    roomNumberPlaceholder: "Quarto 402",
    guestSurnamePlaceholder: "Silva",

    pricingTitle: "Planos Transparentes para Qualquer Dimensão",
    pricingSubtitle: "Escale a satisfação dos hóspedes e automatize 80% dos pedidos da receção.",
    monthlyBilling: "Faturação Mensal",
    annualBilling: "Faturação Anual",
    saveBadge: "Poupe 20% + Setup Grátis",
    billedAnnually: "Cobrado anualmente",
    billedMonthly: "Cobrado mensalmente",
    monthlyPerUnit: "/ mês",
    noCommitment: "Sem fidelização • Cancele quando quiser",
    freeSetupBadge: "GRÁTIS 🎁",
    setupFeeLabel: "Taxa de Instalação (Setup):",
    planPopularBadge: "Mais Popular",

    plans: {
      starter: {
        name: "Starter (Airbnb & AL)",
        target: "Propriedades individuais & Pequenos Anfitriões (1 a 3 unidades)",
        desc: "Ideal para anfitriões que querem automatizar check-in, Wi-Fi e dúvidas tardias de hóspedes.",
        features: [
          "1 a 3 Quartos / Apartamentos",
          "Concierge Autónomo em 6 Idiomas",
          "Códigos QR de Alta Resolução",
          "Instruções Automáticas de Wi-Fi e Check-in",
          "Notificações de Pedidos por Email",
          "Garantia de Uptime 99.9%"
        ],
        cta: "Testar 7 Dias Grátis / Começar"
      },
      boutique: {
        name: "Boutique Hotel",
        target: "Hotéis de Charme, Pousadas & B&Bs (4 a 25 quartos)",
        desc: "O sistema completo de gestão de hóspedes: fila de pedidos da receção, upsell e interação por voz.",
        features: [
          "Até 25 Quartos / Suítes",
          "Painel da Receção em Tempo Real",
          "Interação por Voz com IA e Resposta Áudio",
          "Upselling de Room Service e Late Check-out",
          "Editor de Menus e Base de Conhecimento",
          "Suporte Prioritário 24/7 por WhatsApp"
        ],
        cta: "Testar 7 Dias Grátis / Subscrever"
      },
      enterprise: {
        name: "Resort & Enterprise",
        target: "Resorts, Cadeias Hoteleiras & Gestoras de Alojamento (25+ unidades)",
        desc: "Infraestrutura hoteleira empresarial com gestão multi-propriedade e integração com PMS.",
        features: [
          "Quartos e Propriedades Ilimitadas",
          "Painel Central Multi-Propriedade",
          "Integrações & Webhooks para PMS",
          "Gestor de Conta Dedicado",
          "Controlo de Acessos para Equipa",
          "Domínio Personalizado (concierge.seuhotel.com)"
        ],
        cta: "Solicitar Piloto Enterprise"
      }
    },

    roiTitle: "Calculadora de Retorno de Investimento (ROI)",
    roiSubtitle: "Calcule quanto o seu hotel poupa em horas de staff e fatura em vendas adicionais.",
    roomCountLabel: "Número de Quartos / Unidades:",
    frontDeskSavingsLabel: "Poupança em Horas de Staff",
    upsellRevenueLabel: "Receita Extra (Room Service & Late Out)",
    softwareCostLabel: "Custo do Software",
    netRoiLabel: "Retorno Líquido Mensal Estimado",
    roiExplanation: "Com base em médias da hotelaria: poupa ~2.5h de receção por quarto/mês (a 18€/h) e gera ~32€ por quarto/mês em vendas extras de bar e saídas tardias.",

    modalTitle: "Iniciar Teste Piloto Grátis de 7 Dias",
    modalSubtitle: "Teste o Grand Concierge AI em 2 quartos durante 7 dias sem qualquer compromisso.",
    modalHotelName: "Nome do Hotel / Propriedade",
    modalContactName: "Nome do Responsável",
    modalEmail: "Email Profissional",
    modalPhone: "WhatsApp / Telemóvel",
    modalNotes: "Observações ou detalhes da propriedade",
    modalSubmit: "Confirmar Pedido de Teste Piloto",
    modalSuccessTitle: "Pedido de Teste Recebido!",
    modalSuccessDesc: "A nossa equipa entrará em contacto em menos de 2 horas para ativar os expositores QR e configurar o menu.",
    modalClose: "Fechar"
  },

  es: {
    navChatbot: "Conserje del Huésped",
    navStaffDesk: "Panel de Recepción & Tickets",
    navDirectory: "Directorio del Hotel",
    navKnowledge: "Base de Conocimiento IA",
    navEmbed: "Widget y Códigos QR",
    navPricing: "Planes & Tarifas",
    tagline: "Conserje Multilingüe con IA & Gestión de Huéspedes",
    demoBadge: "Demostración Interactiva en Vivo",
    liveBadge: "Activo 24/7",
    trialNotice: "🔥 Oferta Exclusiva: Prueba Piloto de 7 Días en 2 Habitaciones (Sin Tarjeta)",
    trialDays: "7 Días de Prueba Gratis",
    footerRights: "© 2026 Grand Concierge AI SaaS. Diseñado para Hoteles Boutique & Alojamientos Turísticos.",
    footerCapabilities: "6 Idiomas Nativos • Atención 24/7 Autónoma • Pago Inmediato con Stripe",

    staffTitle: "Cola de Tickets y Operaciones de Recepción",
    staffSubtitle: "Peticiones de limpieza, averías, servicio de habitaciones y salida tardía gestionadas en tiempo real.",
    filterAll: "Todas las Categorías",
    filterHousekeeping: "Limpieza y Toallas",
    filterMaintenance: "Mantenimiento",
    filterLateCheckout: "Salida Tardía (Late Check-out)",
    filterRoomService: "Servicio de Habitaciones",
    filterGeneral: "General / Conserjería",
    statusAll: "Todos los Estados",
    statusPending: "Pendiente",
    statusInProgress: "En Proceso",
    statusCompleted: "Completado",
    searchPlaceholder: "Buscar por nº habitación, huésped o solicitud...",
    createTicketBtn: "+ Crear Ticket Manual",
    refreshBtn: "Actualizar Lista",
    noTicketsTitle: "No Hay Tickets",
    noTicketsSubtitle: "No hay solicitudes con los filtros actuales. Las nuevas peticiones del chat aparecerán aquí al instante.",
    roomLabel: "Nº Habitación",
    guestLabel: "Nombre del Huésped",
    categoryLabel: "Departamento",
    titleLabel: "Título de la Solicitud",
    descLabel: "Detalles y Notas",
    cancelBtn: "Cancelar",
    submitTicketBtn: "Registrar Ticket",
    newTicketModalTitle: "Crear Nueva Solicitud de Personal",

    directoryTitle: "Servicios, Gastronomía y Guía del Hotel",
    directorySubtitle: "Directorio completo de restaurantes, bienestar, normas del hotel y atracciones locales.",
    tabDining: "Gastronomía & Room Service",
    tabAmenities: "Piscinas, Spa & Bienestar",
    tabAttractions: "Atracciones Locales & Tours",
    tabPolicies: "Normativa del Hotel & Recepción",
    searchMenuPlaceholder: "Buscar en el menú del restaurante...",
    orderViaChatbot: "Pedir al Conserje",
    askChatbotPrompt: "Consultar al Conserje sobre",
    favoriteBadge: "Favorito",
    serviceIncluded: "Servicio de entrega en habitación incluido.",
    breakfastTitle: "Desayuno Buffet Atlántico",
    poolSpaTitle: "Piscinas Climatizadas & Spa",
    gymTitle: "Gimnasio Technogym",
    parkingTitle: "Aparcamiento & Cargador Eléctrico",

    kbTitle: "Perfil del Hotel y Entrenamiento de IA",
    kbSubtitle: "Configure Wi-Fi, horarios, servicios y normas. El asistente responde al 100% según estos datos.",
    kbSaveSuccess: "¡Perfil y base de conocimiento guardados con éxito!",
    kbSaveBtn: "Guardar Cambios",
    kbResetBtn: "Restaurar por Defecto",
    hotelNameLabel: "Nombre del Hotel / Propiedad",
    defaultLangLabel: "Idioma por Defecto",
    wifiNetLabel: "Nombre de Red Wi-Fi (SSID)",
    wifiPassLabel: "Instrucciones de Conexión Wi-Fi",
    checkInLabel: "Horario de Check-in",
    checkOutLabel: "Horario de Check-out",
    breakfastHoursLabel: "Horario del Desayuno",
    breakfastLocationLabel: "Lugar del Desayuno",
    poolHoursLabel: "Horario de Piscinas",
    spaHoursLabel: "Horario del Spa",
    gymHoursLabel: "Horario del Gimnasio",
    roomServiceHoursLabel: "Horario de Room Service",
    petPolicyLabel: "Política de Mascotas",
    smokingPolicyLabel: "Política de Fumar",
    luggagePolicyLabel: "Custodia de Equipaje",
    parkingDetailsLabel: "Aparcamiento y Vehículos Eléctricos",
    localAttractionsLabel: "Atracciones y Recomendaciones Locales",
    lateCheckoutPolicyLabel: "Política y Tarifas de Late Check-out",
    customPromptLabel: "Prompt del Sistema Personalizado",

    embedTitle: "Código QR para Habitaciones & Acceso Directo",
    embedSubtitle: "Genere soportes y tarjetas en alta resolución para colocar en mesitas de noche.",
    cardPreviewTitle: "Vista Previa del Soporte de Habitación",
    cardPreviewSubtitle: "Imprima y coloque en la habitación para que el huésped escanee al instante.",
    downloadPdfBtn: "Descargar Expositor en PDF (Alta Resolución)",
    copyUrlBtn: "Copiar Enlace del Huésped",
    copiedNotice: "¡Enlace copiado al portapapeles!",
    howItWorksStep1: "1. El huésped escanea el QR con su móvil (sin instalar aplicaciones)",
    howItWorksStep2: "2. El conserje se abre al instante en el idioma del huésped",
    howItWorksStep3: "3. Las solicitudes llegan en tiempo real al panel de recepción",
    guestFacingUrlLabel: "Enlace Directo para Huéspedes",
    roomNumberPlaceholder: "Habitación 402",
    guestSurnamePlaceholder: "García",

    pricingTitle: "Planes Transparentes para Cualquier Hotel",
    pricingSubtitle: "Aumente la satisfacción del huésped y automatice el 80% de las consultas de recepción.",
    monthlyBilling: "Facturación Mensual",
    annualBilling: "Facturación Anual",
    saveBadge: "Ahorre 20% + Setup Gratis",
    billedAnnually: "Facturado anualmente",
    billedMonthly: "Facturado mensualmente",
    monthlyPerUnit: "/ mes",
    noCommitment: "Sin permanencia • Cancele cuando quiera",
    freeSetupBadge: "GRATIS 🎁",
    setupFeeLabel: "Tasa de Instalación:",
    planPopularBadge: "Más Popular",

    plans: {
      starter: {
        name: "Starter (Airbnb & Alquiler Vacacional)",
        target: "Alojamientos individuales y pequeños anfitriones (1 a 3 unidades)",
        desc: "Ideal para anfitriones que desean automatizar el check-in, Wi-Fi y dudas nocturnas.",
        features: [
          "1 a 3 Habitaciones / Apartamentos",
          "Conserje Autónomo en 6 Idiomas",
          "Códigos QR de Alta Definición",
          "Guías Automáticas de Wi-Fi y Check-in",
          "Notificación de Solicitudes por Email",
          "Garantía de Disponibilidad 99.9%"
        ],
        cta: "Probar 7 Días Gratis / Empezar"
      },
      boutique: {
        name: "Hotel Boutique",
        target: "Hoteles Boutique, Casas Rurales & B&Bs (4 a 25 habitaciones)",
        desc: "El sistema integral para hoteles: panel de tickets, venta de room service y voz interactiva.",
        features: [
          "Hasta 25 Habitaciones / Suites",
          "Panel de Recepción en Tiempo Real",
          "Interacción por Voz con IA y Salida de Audio",
          "Upselling de Room Service y Late Check-out",
          "Editor de Menús y Base de Conocimiento",
          "Soporte Prioritario 24/7 por WhatsApp"
        ],
        cta: "Probar 7 Días Gratis / Suscribirse"
      },
      enterprise: {
        name: "Resort & Enterprise",
        target: "Resorts, Cadenas y Gestores con múltiples propiedades (25+ unidades)",
        desc: "Infraestructura hotelera corporativa con gestión multipropiedad e integración PMS.",
        features: [
          "Habitaciones y Hoteles Ilimitados",
          "Panel Central Multi-Propiedad",
          "Integraciones y Webhooks para PMS",
          "Gestor de Cuenta Dedicado",
          "Control de Permisos de Empleados",
          "Dominio Personalizado (conserje.suhotel.com)"
        ],
        cta: "Solicitar Piloto Enterprise"
      }
    },

    roiTitle: "Calculadora de Retorno de Inversión (ROI)",
    roiSubtitle: "Calcule cuánto ahorra su hotel en horas de personal y factura en ventas adicionales.",
    roomCountLabel: "Número de Habitaciones:",
    frontDeskSavingsLabel: "Ahorro en Horas de Personal",
    upsellRevenueLabel: "Ingresos Extra (Room Service & Salida Tardía)",
    softwareCostLabel: "Coste del Software",
    netRoiLabel: "Retorno Neto Mensual Estimado",
    roiExplanation: "Basado en medias hoteleras: ahorra ~2.5h de recepción por habitación/mes y genera ~35$ en servicios adicionales.",

    modalTitle: "Iniciar Prueba Piloto de 7 Días Gratis",
    modalSubtitle: "Pruebe Grand Concierge AI en 2 habitaciones durante 7 días sin compromiso.",
    modalHotelName: "Nombre del Hotel / Propiedad",
    modalContactName: "Persona de Contacto",
    modalEmail: "Correo Electrónico",
    modalPhone: "WhatsApp / Teléfono",
    modalNotes: "Detalles o notas sobre la propiedad",
    modalSubmit: "Confirmar Solicitud de Piloto",
    modalSuccessTitle: "¡Solicitud Recibida!",
    modalSuccessDesc: "Nuestro equipo se pondrá en contacto en menos de 2 horas para activar sus soportes QR.",
    modalClose: "Cerrar"
  },

  fr: {
    navChatbot: "Concierge Voyageur",
    navStaffDesk: "Réception & Billetterie",
    navDirectory: "Guide & Services de l'Hôtel",
    navKnowledge: "Base IA de l'Établissement",
    navEmbed: "Widget & QR Codes",
    navPricing: "Tarifs & Abonnements",
    tagline: "Conciergerie IA Multilingue & Gestion Hôtelière",
    demoBadge: "Démonstration Interactive en Direct",
    liveBadge: "Actif 24/7",
    trialNotice: "🔥 Offre Pilote : 7 Jours d'Essai Gratuit sur 2 Chambres (Sans Carte Bancaire)",
    trialDays: "7 Jours d'Essai Gratuit",
    footerRights: "© 2026 Grand Concierge AI SaaS. Développé pour Hôtels de Luxe, Meublés & B&Bs.",
    footerCapabilities: "6 Langues Natives • Service 24/7 Autonome • Paiement Stripe Immédiat",

    staffTitle: "File des Demandes & Opérations Réception",
    staffSubtitle: "Demandes de ménage, maintenance, room service et départ tardif reçues en temps réel.",
    filterAll: "Toutes les Catégories",
    filterHousekeeping: "Gouvernante / Ménage",
    filterMaintenance: "Maintenance & Technique",
    filterLateCheckout: "Départ Tardif (Late Check-out)",
    filterRoomService: "Room Service",
    filterGeneral: "Général / Conciergerie",
    statusAll: "Tous les Statuts",
    statusPending: "En Attente",
    statusInProgress: "En Cours",
    statusCompleted: "Terminé",
    searchPlaceholder: "Rechercher par chambre, nom du client ou demande...",
    createTicketBtn: "+ Créer Ticket Manuel",
    refreshBtn: "Actualiser la Liste",
    noTicketsTitle: "Aucune Demande Trouvée",
    noTicketsSubtitle: "Aucune demande ne correspond aux filtres. Les nouvelles demandes envoyées par les clients apparaîtront ici instantanément.",
    roomLabel: "N° Chambre",
    guestLabel: "Nom du Client",
    categoryLabel: "Département",
    titleLabel: "Titre de la Demande",
    descLabel: "Détails & Remarques",
    cancelBtn: "Annuler",
    submitTicketBtn: "Enregistrer le Ticket",
    newTicketModalTitle: "Créer une Nouvelle Demande",

    directoryTitle: "Services, Carte du Restaurant & Guide Voyageur",
    directorySubtitle: "Découvrez nos prestations bien-être, horaires des repas, règlements et conseils locaux.",
    tabDining: "Restauration & Room Service",
    tabAmenities: "Piscines, Spa & Bien-être",
    tabAttractions: "Sites Touristiques & Visites",
    tabPolicies: "Règlement & Réception",
    searchMenuPlaceholder: "Rechercher dans le menu du restaurant...",
    orderViaChatbot: "Commander via le Concierge",
    askChatbotPrompt: "Demander au Concierge à propos de",
    favoriteBadge: "Coup de Cœur",
    serviceIncluded: "Service de livraison en chambre inclus.",
    breakfastTitle: "Petit-Déjeuner Buffet Atlantique",
    poolSpaTitle: "Piscines Chauffées & Thalasso Spa",
    gymTitle: "Espace Fitness Technogym",
    parkingTitle: "Parking Couvert & Bornes Électriques",

    kbTitle: "Profil de l'Hôtel & Entraînement de l'IA",
    kbSubtitle: "Configurez le Wi-Fi, les horaires des repas, les prestations et règlements. L'IA s'appuie à 100% sur ces données.",
    kbSaveSuccess: "Profil et base de connaissances enregistrés avec succès !",
    kbSaveBtn: "Enregistrer les Modifications",
    kbResetBtn: "Rétablir les Valeurs par Défaut",
    hotelNameLabel: "Nom de l'Établissement",
    defaultLangLabel: "Langue par Défaut",
    wifiNetLabel: "Nom du Réseau Wi-Fi (SSID)",
    wifiPassLabel: "Instructions de Connexion Wi-Fi",
    checkInLabel: "Heure d'Arrivée (Check-in)",
    checkOutLabel: "Heure de Départ (Check-out)",
    breakfastHoursLabel: "Horaires du Petit-Déjeuner",
    breakfastLocationLabel: "Lieu du Petit-Déjeuner",
    poolHoursLabel: "Horaires des Piscines",
    spaHoursLabel: "Horaires du Spa",
    gymHoursLabel: "Horaires de la Salle de Sport",
    roomServiceHoursLabel: "Horaires du Room Service",
    petPolicyLabel: "Politique Animaux",
    smokingPolicyLabel: "Politique Tabac",
    luggagePolicyLabel: "Consigne à Bagages",
    parkingDetailsLabel: "Parking & Bornes de Recharge",
    localAttractionsLabel: "Recommandations & Visites Locales",
    lateCheckoutPolicyLabel: "Départ Tardif & Tarifs",
    customPromptLabel: "Prompt Système Personnalisé",

    embedTitle: "QR Code Chambre & Accès Concierge",
    embedSubtitle: "Générez des chevalets et supports haute définition pour les tables de chevet.",
    cardPreviewTitle: "Aperçu du Chevalet de Chambre",
    cardPreviewSubtitle: "À imprimer et disposer en chambre pour une utilisation immédiate par le client.",
    downloadPdfBtn: "Télécharger le Chevalet en PDF Haute Résolution",
    copyUrlBtn: "Copier le Lien Client",
    copiedNotice: "Lien copié dans le presse-papiers !",
    howItWorksStep1: "1. Le client scanne le QR code avec son smartphone (sans application)",
    howItWorksStep2: "2. Le concierge s'ouvre directement dans la langue du voyageur",
    howItWorksStep3: "3. Les demandes (serviettes, repas, départ tardif) arrivent en réception",
    guestFacingUrlLabel: "Lien Direct Voyageur",
    roomNumberPlaceholder: "Chambre 402",
    guestSurnamePlaceholder: "Dupont",

    pricingTitle: "Des Tarifs Transparents pour Chaque Établissement",
    pricingSubtitle: "Améliorez l'expérience client et automatisez 80% des demandes courantes.",
    monthlyBilling: "Facturation Mensuelle",
    annualBilling: "Facturation Annuelle",
    saveBadge: "Économisez 20% + Configuration Offerte",
    billedAnnually: "Facturé annuellement",
    billedMonthly: "Facturé mensuellement",
    monthlyPerUnit: "/ mois",
    noCommitment: "Sans engagement • Résiliez à tout moment",
    freeSetupBadge: "OFFERT 🎁",
    setupFeeLabel: "Frais de configuration :",
    planPopularBadge: "Le Plus Choisi",

    plans: {
      starter: {
        name: "Starter (Airbnb & Meublés)",
        target: "Hébergements individuels & Superhosts (1 à 3 logements)",
        desc: "Parfait pour automatiser le check-in, le Wi-Fi et les questions nocturnes des voyageurs.",
        features: [
          "1 à 3 Chambres / Logements",
          "Concierge Autonome en 6 Langues",
          "QR Codes Haute Définition Imprimables",
          "Guides Wi-Fi et Check-in Automatisés",
          "Notifications des Demandes par Email",
          "Garantie de Disponibilité 99.9%"
        ],
        cta: "Essai 7 Jours Gratuit / Démarrer"
      },
      boutique: {
        name: "Hôtel Boutique",
        target: "Hôtels de Charme, Auberges & B&Bs (4 à 25 chambres)",
        desc: "La solution hôtelière complète : tableau de bord réception, upsell de restauration et voix interactive.",
        features: [
          "Jusqu'à 25 Chambres / Suites",
          "File de Réception en Temps Réel",
          "Interaction Vocale IA avec Synthèse Vocale",
          "Upselling Room Service & Départ Tardif",
          "Éditeur de Menus et Base de Connaissances",
          "Support Prioritaire 24/7 sur WhatsApp"
        ],
        cta: "Essai 7 Jours Gratuit / S'abonner"
      },
      enterprise: {
        name: "Resort & Enterprise",
        target: "Resorts, Groupes Hôteliers & Gestionnaires (25+ chambres)",
        desc: "Infrastructure pour grands établissements avec gestion multi-hôtels et intégration PMS.",
        features: [
          "Chambres et Établissements Illimités",
          "Administration Centrale Multi-Hôtels",
          "Webhooks et Connecteurs PMS",
          "Gestionnaire de Compte Dédié",
          "Gestion des Rôles et Droits Équipe",
          "Nom de Domaine Dédié (concierge.votrehotel.com)"
        ],
        cta: "Demander un Pilote Enterprise"
      }
    },

    roiTitle: "Calculateur de Retour sur Investissement (ROI)",
    roiSubtitle: "Estimez les gains de temps du personnel et les revenus additionnels générés.",
    roomCountLabel: "Nombre de Chambres :",
    frontDeskSavingsLabel: "Heures de Réception Économisées",
    upsellRevenueLabel: "Revenus Supplémentaires (Room Service & Départ Tardif)",
    softwareCostLabel: "Coût de l'Abonnement",
    netRoiLabel: "Gain Net Mensuel Estimé",
    roiExplanation: "Basé sur les standards hôteliers : économie de ~2.5h de travail par chambre/mois et ~35€ de ventes additionnelles.",

    modalTitle: "Démarrer l'Essai Pilote Gratuit de 7 Jours",
    modalSubtitle: "Testez Grand Concierge AI sur 2 chambres pendant 7 jours sans aucun engagement.",
    modalHotelName: "Nom de l'Hôtel / Établissement",
    modalContactName: "Nom du Responsable",
    modalEmail: "Email Professionnel",
    modalPhone: "WhatsApp / Téléphone",
    modalNotes: "Remarques ou détails sur l'établissement",
    modalSubmit: "Confirmer la Demande Pilote",
    modalSuccessTitle: "Demande Pilote Reçue !",
    modalSuccessDesc: "Notre équipe vous contactera en moins de 2 heures pour configurer vos QR codes.",
    modalClose: "Fermer"
  },

  de: {
    navChatbot: "Gäste-Concierge",
    navStaffDesk: "Rezeption & Ticket-System",
    navDirectory: "Hotelverzeichnis",
    navKnowledge: "KI-Wissensdatenbank",
    navEmbed: "Widget & QR-Codes",
    navPricing: "Preise & Tarife",
    tagline: "Mehrsprachiger KI-Concierge & Hotelmanagement",
    demoBadge: "Interaktive Live-Demo",
    liveBadge: "24/7 Aktiv",
    trialNotice: "🔥 Exklusives Angebot: 7-Tage-Testlauf auf 2 Zimmern (Keine Kreditkarte nötig)",
    trialDays: "7 Tage Kostenlos Testen",
    footerRights: "© 2026 Grand Concierge AI SaaS. Entwickelt für Boutique-Hotels, Ferienwohnungen & B&Bs.",
    footerCapabilities: "6 Muttersprachen • Autonomer 24/7 Service • Sofortige Stripe-Abrechnung",

    staffTitle: "Rezeptions- & Service-Ticket-Übersicht",
    staffSubtitle: "Echtzeit-Anfragen für Zimmerreinigung, Technik, Zimmerservice und späten Check-out.",
    filterAll: "Alle Kategorien",
    filterHousekeeping: "Housekeeping / Reinigung",
    filterMaintenance: "Wartung & Technik",
    filterLateCheckout: "Später Check-out",
    filterRoomService: "Zimmerservice",
    filterGeneral: "Allgemeine Anfragen",
    statusAll: "Alle Status",
    statusPending: "Ausstehend",
    statusInProgress: "In Bearbeitung",
    statusCompleted: "Erledigt",
    searchPlaceholder: "Nach Zimmernummer, Gast oder Anliegen suchen...",
    createTicketBtn: "+ Manuelles Ticket Erstellen",
    refreshBtn: "Liste Aktualisieren",
    noTicketsTitle: "Keine Tickets Gefunden",
    noTicketsSubtitle: "Keine Anfragen für die gewählten Filter vorhanden. Neue Gästewünsche erscheinen hier sofort.",
    roomLabel: "Zimmer-Nr.",
    guestLabel: "Name des Gastes",
    categoryLabel: "Abteilung",
    titleLabel: "Titel der Anfrage",
    descLabel: "Details & Notizen",
    cancelBtn: "Abbrechen",
    submitTicketBtn: "Ticket Speichern",
    newTicketModalTitle: "Neues Service-Ticket Erstellen",

    directoryTitle: "Hotel-Ausstattung, Gastronomie & Gästeführer",
    directorySubtitle: "Vollständige Übersicht über Speisekarten, Wellness, Hotelrichtlinien und lokale Highlights.",
    tabDining: "Gastronomie & Zimmerservice",
    tabAmenities: "Pools, Spa & Wellness",
    tabAttractions: "Ausflugsziele & Touren",
    tabPolicies: "Hotelrichtlinien & Rezeption",
    searchMenuPlaceholder: "In Restaurant- & Barkarte suchen...",
    orderViaChatbot: "Über Concierge Bestellen",
    askChatbotPrompt: "Concierge fragen über",
    favoriteBadge: "Beliebt",
    serviceIncluded: "Zimmerzustellung inklusive.",
    breakfastTitle: "Atlantik Frühstücksbuffet",
    poolSpaTitle: "Beheizte Pools & Thalasso Spa",
    gymTitle: "Fitnesscenter Technogym",
    parkingTitle: "Tiefgarage & E-Ladestationen",

    kbTitle: "Hotelprofil & Training der KI-Wissensdatenbank",
    kbSubtitle: "Hinterlegen Sie WLAN-Daten, Essenszeiten, Angebote und Regeln. Die KI stützt 100% ihrer Antworten auf diese Angaben.",
    kbSaveSuccess: "Hotelprofil und Wissensdatenbank erfolgreich gespeichert!",
    kbSaveBtn: "Änderungen Speichern",
    kbResetBtn: "Auf Standard Zurücksetzen",
    hotelNameLabel: "Hotelname / Unterkunft",
    defaultLangLabel: "Standardsprache",
    wifiNetLabel: "WLAN-Netzwerkname (SSID)",
    wifiPassLabel: "WLAN-Zugangsanleitung",
    checkInLabel: "Check-in Zeit",
    checkOutLabel: "Check-out Zeit",
    breakfastHoursLabel: "Frühstückszeiten",
    breakfastLocationLabel: "Frühstücksort",
    poolHoursLabel: "Pool-Öffnungszeiten",
    spaHoursLabel: "Spa- & Wellnesszeiten",
    gymHoursLabel: "Fitness-Öffnungszeiten",
    roomServiceHoursLabel: "Zimmerservice-Zeiten",
    petPolicyLabel: "Haustier-Richtlinie",
    smokingPolicyLabel: "Raucher-Richtlinie",
    luggagePolicyLabel: "Gepäckaufbewahrung",
    parkingDetailsLabel: "Parkplatz & E-Ladestation",
    localAttractionsLabel: "Sehenswürdigkeiten & Ausflugstipps",
    lateCheckoutPolicyLabel: "Late Check-out Bedingungen & Gebühren",
    customPromptLabel: "Individueller KI-System-Prompt",

    embedTitle: "Zimmer-QR-Code & Digitaler Concierge",
    embedSubtitle: "Erstellen Sie hochauflösende QR-Code-Aufsteller für Nachttische und Schlüsselkarten.",
    cardPreviewTitle: "Vorschau des Hotelzimmer-Aufstellers",
    cardPreviewSubtitle: "Ausdrucken und im Zimmer platzieren für sofortige Nutzung durch Gäste.",
    downloadPdfBtn: "Aufsteller als hochauflösendes PDF Herunterladen",
    copyUrlBtn: "Gäste-Link Kopieren",
    copiedNotice: "Link in die Zwischenablage kopiert!",
    howItWorksStep1: "1. Gast scannt den QR-Code mit dem Smartphone (keine App nötig)",
    howItWorksStep2: "2. Concierge öffnet sich direkt in der Muttersprache des Gastes",
    howItWorksStep3: "3. Wünsche (Handtücher, Spätabreise, Essen) landen sofort an der Rezeption",
    guestFacingUrlLabel: "Direkter Gäste-Weblink",
    roomNumberPlaceholder: "Zimmer 402",
    guestSurnamePlaceholder: "Schmidt",

    pricingTitle: "Transparente Tarife für Jede Hotelgröße",
    pricingSubtitle: "Gästezufriedenheit steigern und 80% der Routinefragen an der Rezeption automatisieren.",
    monthlyBilling: "Monatliche Abrechnung",
    annualBilling: "Jährliche Abrechnung",
    saveBadge: "20% Sparen + Kostenlose Einrichtung",
    billedAnnually: "Jährlich abgerechnet",
    billedMonthly: "Monatlich abgerechnet",
    monthlyPerUnit: "/ Monat",
    noCommitment: "Keine Vertragsbindung • Jederzeit kündbar",
    freeSetupBadge: "KOSTENLOS 🎁",
    setupFeeLabel: "Einrichtungsgebühr:",
    planPopularBadge: "Beliebteste Wahl",

    plans: {
      starter: {
        name: "Starter (Ferienwohnungen & STR)",
        target: "Einzelne Ferienunterkünfte & Hosts (1 bis 3 Einheiten)",
        desc: "Ideal für Gastgeber zur Automatisierung von Check-in, WLAN und späten Gästefragen.",
        features: [
          "1 bis 3 Zimmer / Apartments",
          "Autonomer KI-Concierge in 6 Sprachen",
          "Druckbare hochauflösende QR-Codes",
          "Automatische WLAN- und Anreiseanleitungen",
          "Benachrichtigungen per E-Mail",
          "99.9% Verfügbarkeitsgarantie"
        ],
        cta: "7 Tage Kostenlos Testen / Starten"
      },
      boutique: {
        name: "Boutique Hotel",
        target: "Boutique-Hotels, Gasthöfe & B&Bs (4 bis 25 Zimmer)",
        desc: "Das umfassende Gast-System: Rezeptionsübersicht, Room-Service-Verkäufe und Sprachinteraktion.",
        features: [
          "Bis zu 25 Zimmer / Suiten",
          "Echtzeit-Rezeptions-Dashboard",
          "Sprachgesteuerte KI-Interaktion & Audioausgabe",
          "Zusatzumsatz mit Zimmerservice & Late Check-out",
          "Menü-Editor & Wissensdatenbank",
          "Prioritärer 24/7 Support über WhatsApp"
        ],
        cta: "7 Tage Kostenlos Testen / Abonnieren"
      },
      enterprise: {
        name: "Resort & Enterprise",
        target: "Resorts, Hotelketten & Hausverwaltungen (25+ Zimmer)",
        desc: "Enterprise-Hotel-Infrastruktur mit Multi-Property-Verwaltung und PMS-Schnittstellen.",
        features: [
          "Unbegrenzte Zimmer und Standorte",
          "Zentrale Multi-Hotel-Verwaltung",
          "PMS- & Channel-Manager-Webhooks",
          "Persönlicher Account Manager",
          "Erweitertes Rollen- & Rechtesystem",
          "Eigene Domain (concierge.ihrhotel.de)"
        ],
        cta: "Enterprise-Pilot Anfordern"
      }
    },

    roiTitle: "ROI-Rechner für Hotels",
    roiSubtitle: "Berechnen Sie Zeiteinsparungen des Personals und zusätzliche Einnahmen.",
    roomCountLabel: "Anzahl der Zimmer:",
    frontDeskSavingsLabel: "Eingesparte Rezeptionsstunden",
    upsellRevenueLabel: "Zusatzumsatz (Zimmerservice & Spätabreise)",
    softwareCostLabel: "Softwarekosten",
    netRoiLabel: "Geschätzter monatlicher Nettogewinn",
    roiExplanation: "Basierend auf Branchendaten: spart ~2.5 Rezeptionsstunden pro Zimmer/Monat und erzielt ~35€ an Zusatzverkäufen.",

    modalTitle: "Kostenlosen 7-Tage-Pilotlauf Starten",
    modalSubtitle: "Testen Sie Grand Concierge AI 7 Tage lang auf 2 Zimmern – völlig unverbindlich.",
    modalHotelName: "Name des Hotels / Unterkunft",
    modalContactName: "Ansprechpartner",
    modalEmail: "Geschäftliche E-Mail",
    modalPhone: "WhatsApp / Telefon",
    modalNotes: "Besondere Anforderungen oder Notizen",
    modalSubmit: "Testlauf Anfordern",
    modalSuccessTitle: "Anfrage Erhalten!",
    modalSuccessDesc: "Unser Team meldet sich innerhalb von 2 Stunden zur Einrichtung Ihrer QR-Aufsteller.",
    modalClose: "Schließen"
  },

  it: {
    navChatbot: "Concierge Ospiti",
    navStaffDesk: "Reception & Richieste",
    navDirectory: "Guida & Servizi Hotel",
    navKnowledge: "Base di Conoscenza IA",
    navEmbed: "Widget & Codici QR",
    navPricing: "Piani & Prezzi",
    tagline: "Concierge IA Multilingue & Gestione Operativa",
    demoBadge: "Demo Interattiva Live",
    liveBadge: "Attivo 24/7",
    trialNotice: "🔥 Offerta Speciale: Prova Pilota di 7 Giorni su 2 Camere (Senza Carta di Credito)",
    trialDays: "7 Giorni di Prova Gratis",
    footerRights: "© 2026 Grand Concierge AI SaaS. Creato per Hotel Boutique, B&B & Strutture Ricettive.",
    footerCapabilities: "6 Lingue Native • Servizio 24/7 Autonomo • Pagamento Diretto con Stripe",

    staffTitle: "Gestione Richieste & Reception",
    staffSubtitle: "Richieste di pulizia, manutenzione, servizio in camera e late check-out in tempo reale.",
    filterAll: "Tutte le Categorie",
    filterHousekeeping: "Governante / Pulizie",
    filterMaintenance: "Manutenzione",
    filterLateCheckout: "Late Check-out",
    filterRoomService: "Servizio in Camera",
    filterGeneral: "Generale / Concierge",
    statusAll: "Tutti gli Stati",
    statusPending: "In Attesa",
    statusInProgress: "In Corso",
    statusCompleted: "Completato",
    searchPlaceholder: "Cerca per numero camera, ospite o richiesta...",
    createTicketBtn: "+ Crea Ticket Manuale",
    refreshBtn: "Aggiorna Lista",
    noTicketsTitle: "Nessuna Richiesta Trovata",
    noTicketsSubtitle: "Nessuna richiesta corrisponde ai filtri selezionati. Le nuove richieste appariranno qui immediatamente.",
    roomLabel: "N° Camera",
    guestLabel: "Nome dell'Ospite",
    categoryLabel: "Reparto",
    titleLabel: "Titolo della Richiesta",
    descLabel: "Dettagli & Note",
    cancelBtn: "Annulla",
    submitTicketBtn: "Registra Ticket",
    newTicketModalTitle: "Crea Nuova Richiesta per lo Staff",

    directoryTitle: "Servizi, Ristorazione & Guida dell'Hotel",
    directorySubtitle: "Guida completa ai menu, benessere, regolamento dell'hotel e attrazioni locali.",
    tabDining: "Ristorazione & Servizio in Camera",
    tabAmenities: "Piscine, Spa & Benessere",
    tabAttractions: "Attrazioni Locali & Tour",
    tabPolicies: "Regole dell'Hotel & Reception",
    searchMenuPlaceholder: "Cerca nel menu del ristorante...",
    orderViaChatbot: "Ordina tramite Concierge",
    askChatbotPrompt: "Chiedi al Concierge su",
    favoriteBadge: "Preferito",
    serviceIncluded: "Servizio di consegna in camera incluso.",
    breakfastTitle: "Colazione a Buffet Atlantico",
    poolSpaTitle: "Piscine Riscaldate & Marina Spa",
    gymTitle: "Palestra Technogym",
    parkingTitle: "Garage Coperto & Ricarica Auto Elettriche",

    kbTitle: "Profilo Hotel & Addestramento IA",
    kbSubtitle: "Configura Wi-Fi, orari pasti, servizi e regole. L'assistente IA si basa al 100% su queste informazioni.",
    kbSaveSuccess: "Profilo e base di conoscenza salvati con successo!",
    kbSaveBtn: "Salva Modifiche",
    kbResetBtn: "Ripristina Predefiniti",
    hotelNameLabel: "Nome della Struttura",
    defaultLangLabel: "Lingua Predefinita",
    wifiNetLabel: "Nome Rete Wi-Fi (SSID)",
    wifiPassLabel: "Istruzioni di Accesso Wi-Fi",
    checkInLabel: "Orario Check-in",
    checkOutLabel: "Orario Check-out",
    breakfastHoursLabel: "Orario Colazione",
    breakfastLocationLabel: "Luogo Colazione",
    poolHoursLabel: "Orario Piscine",
    spaHoursLabel: "Orario Spa",
    gymHoursLabel: "Orario Palestra",
    roomServiceHoursLabel: "Orario Servizio in Camera",
    petPolicyLabel: "Politica Animali Domestici",
    smokingPolicyLabel: "Politica Fumo",
    luggagePolicyLabel: "Deposito Bagagli",
    parkingDetailsLabel: "Parcheggio & Ricarica Elettrica",
    localAttractionsLabel: "Attrazioni & Consigli Locali",
    lateCheckoutPolicyLabel: "Politica & Tariffe Late Check-out",
    customPromptLabel: "Prompt di Sistema Personalizzato",

    embedTitle: "Codice QR per Camera & Accesso Digitale",
    embedSubtitle: "Genera espositori e tessere in alta risoluzione per comodini e scrivanie.",
    cardPreviewTitle: "Anteprima dell'Espositore da Camera",
    cardPreviewSubtitle: "Da stampare e posizionare in camera per l'accesso immediato dell'ospite.",
    downloadPdfBtn: "Scarica Espositore in PDF ad Alta Risoluzione",
    copyUrlBtn: "Copia Link Ospite",
    copiedNotice: "Link copiato negli appunti!",
    howItWorksStep1: "1. L'ospite inquadra il QR code con lo smartphone (nessuna app da installare)",
    howItWorksStep2: "2. Il concierge si apre istantaneamente nella lingua madre dell'ospite",
    howItWorksStep3: "3. Le richieste (asciugamani, pasti, late check-out) arrivano subito alla reception",
    guestFacingUrlLabel: "Link Diretto per gli Ospiti",
    roomNumberPlaceholder: "Camera 402",
    guestSurnamePlaceholder: "Rossi",

    pricingTitle: "Piani Trasparenti per Tutte le Strutture",
    pricingSubtitle: "Migliora l'esperienza degli ospiti e automatizza l'80% delle richieste della reception.",
    monthlyBilling: "Fatturazione Mensile",
    annualBilling: "Fatturazione Annuale",
    saveBadge: "Risparmia 20% + Setup Gratuito",
    billedAnnually: "Fatturato annualmente",
    billedMonthly: "Fatturato mensilmente",
    monthlyPerUnit: "/ mese",
    noCommitment: "Nessun vincolo • Cancella quando vuoi",
    freeSetupBadge: "GRATUITO 🎁",
    setupFeeLabel: "Costo di Installazione:",
    planPopularBadge: "Più Popolare",

    plans: {
      starter: {
        name: "Starter (Airbnb & Case Vacanza)",
        target: "Strutture individuali & Host (da 1 a 3 unità)",
        desc: "Ideale per automatizzare check-in, Wi-Fi e domande notturne dei viaggiatori.",
        features: [
          "Da 1 a 3 Camere / Appartamenti",
          "Concierge Autonomo in 6 Lingue",
          "Codici QR ad Alta Risoluzione Stampabili",
          "Guide Wi-Fi e Check-in Automatiche",
          "Notifiche Richieste via Email",
          "Garanzia di Uptime 99.9%"
        ],
        cta: "Prova 7 Giorni Gratis / Inizia Ora"
      },
      boutique: {
        name: "Boutique Hotel",
        target: "Hotel di Charme, Agriturismi & B&B (da 4 a 25 camere)",
        desc: "La suite completa: bacheca richieste reception, upselling pasti e voce interattiva.",
        features: [
          "Fino a 25 Camere / Suite",
          "Pannello Reception in Tempo Reale",
          "Interazione Vocale IA con Risposta Audio",
          "Upselling Servizio in Camera & Late Check-out",
          "Editor Menu e Base di Conoscenza",
          "Supporto Prioritario 24/7 su WhatsApp"
        ],
        cta: "Prova 7 Giorni Gratis / Abbonati"
      },
      enterprise: {
        name: "Resort & Enterprise",
        target: "Resort, Grand Hotel & Catene Alberghiere (25+ camere)",
        desc: "Infrastruttura per grandi strutture con gestione multi-hotel e integrazione PMS.",
        features: [
          "Camere e Strutture Illimitate",
          "Pannello Centrale Multi-Struttura",
          "Integrazioni & Webhook per PMS",
          "Account Manager Dedicato",
          "Gestione Ruoli e Permessi Staff",
          "Dominio Personalizzato (concierge.tuohotel.it)"
        ],
        cta: "Richiedi Pilota Enterprise"
      }
    },

    roiTitle: "Calcolatore ROI per Strutture Ricettive",
    roiSubtitle: "Calcola il risparmio di ore alla reception e l'aumento delle vendite extra.",
    roomCountLabel: "Numero di Camere:",
    frontDeskSavingsLabel: "Ore di Reception Risparmiate",
    upsellRevenueLabel: "Ricavi Extra (Servizio in Camera & Late Check-out)",
    softwareCostLabel: "Costo del Software",
    netRoiLabel: "Ritorno Netto Mensile",
    roiExplanation: "Basato sulle medie di settore: risparmio di ~2.5 ore di reception a camera/mese e ~35€ di vendite aggiuntive.",

    modalTitle: "Avvia Prova Pilota Gratuita di 7 Giorni",
    modalSubtitle: "Testa Grand Concierge AI su 2 camere per 7 giorni senza alcun vincolo.",
    modalHotelName: "Nome dell'Hotel / Struttura",
    modalContactName: "Persona di Riferimento",
    modalEmail: "Email Aziendale",
    modalPhone: "WhatsApp / Telefono",
    modalNotes: "Note o dettagli della struttura",
    modalSubmit: "Conferma Richiesta Pilota",
    modalSuccessTitle: "Richiesta Ricevuta!",
    modalSuccessDesc: "Il nostro team ti contatterà entro 2 ore per configurare i tuoi espositori QR.",
    modalClose: "Chiudi"
  }
};
